- name: Demo on when conditions
  hosts: localhost
  vars:
    URL: google.com
    a: 10
    ACTION: true

  tasks:
    - name: condition on strings
      when: URL == "google.com"
      debug:
        msg: Hello

    - name: condition on strings
      when: URL != "google.com"
      debug:
        msg: world

    - name : Condition on numbers
      when: a == 10
      debug:
        msg: user

    - name : Condition on numbers
      when: a <= 10
      debug:
        msg: welcome

    - name: Run if action is true
      when: ACTION
      debug:
        msg: Hello

    - name: Run if action is not true
      when:  not ACTION
      debug:
        msg: world

    - name: Run if variable B is defined
      when: B is defined
      debug:
        msg: it is defined

    - name: Run if variable B is not defined and a is less than 10
      when: B is not defined and a <= 10
      debug:
        msg: hello




