- name: Setup MySQL repo file
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL server
  yum:
    name: mysql-community-server
    state: present

- name: Start MySQL service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check the default password
  shell: echo "show databases;" | mysql -uroot -pRoboShop@1
  register: default_mysql_check

- name: Grab default password
  shell: grep 'A temporary password' /var/log/mysqld.log  | awk '{print $NF}'
  register: out
