- name: Install NodeJs
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Add a Roboshop application user
  ansible.builtin.user:
    name: roboshop

- name: Download GitHub
  include_tasks:
    file: download.yml

- name: copy the extracted content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install Catalogue dependencies
  community.general.npm:
    path: /home/roboshop/catalogue/
    state: latest
  become_user: roboshop

- name: Update systemd configuration
  copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: restrat xatalogue service
  systemd:
    name: catalogue
    state: started
    enabled: yes
    daemon_reload: yes


