- name: Install NodeJs
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Add a Roboshop application user
  ansible.builtin.user:
    name: roboshop

- name: Download GitHub
  include_tasks:
    file: download.yml

- name: copy the extracted content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    owner: roboshop
    group: roboshop

