- name: Install NodeJs
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Download App code  & Add App User
  include_tasks:
    file: download.yml

- name: Install {{COMPONENT}} dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}/
    state: latest
  become_user: roboshop

- name: Setup Systemd
  include_tasks:
    file: setup-systemd.yml

- name: Install Node Exporter
  include_tasks:
    file: node-exporter.yml




